Repository RydeTec/rcce2, pull requests merged in 2025-01, with the labels that each got.

#29 Update the default font to Verdana
  .gitignore
  bin/tools/FontGen/Title.bmp
  bin/tools/FontGen/Title.dat
  data/UI/Fonts/Bubble.bmp
  data/UI/Fonts/Bubble.dat
  data/UI/Fonts/Title.bmp
  data/UI/Fonts/Title.dat
Labels: enhancement

#28 Update ReadMe with some source instructions and extras
  ReadMe.md
Labels: documentation

#31 [HOTFIX] Fix importing assets into GUE
  src/GUE.bb
Labels: bug

#36 [ENHANCE] Better 3rd person camera behavior
  src/Client.bb
  src/Modules/Interface3D.bb
Labels: enhancement

#37 [ENHANCE] Dismiss current target if target details window closed
  src/Modules/Interface3D.bb
Labels: enhancement

#38 [ENHANCE] Add right-click context menu
  data/Server Data/Scripts/Click_Trainer.rsl
  data/Server Data/Scripts/Default.rsl
  src/Modules/Interface3D.bb
  src/Modules/Packets.bb
  src/Modules/ServerNet.bb
Labels: enhancement

#42 Bugfix: fix trading
  data/Areas/Plains.dat
  data/Server Data/Actors.dat
  data/Server Data/Areas/Plains.dat
  data/Server Data/Misc.dat
  data/Server Data/Scripts/Click_Trainer.rsl
  data/Server Data/Scripts/Default.rsl
  data/Server Data/Scripts/Spawn_Test.rsl
  src/Client.bb
  src/Modules/Interface3D.bb
  src/Modules/Packets.bb
  src/Modules/ServerNet.bb
Labels: bug
